version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      auto_route:
        patterns:
          - "auto_route*"
      freezed:
        patterns:
          - "freezed*"
      graphql:
        patterns:
          - "graphql*"
      riverpod:
        patterns:
          - "*riverpod*"
